Models/BidProjectFees.cs
namespace BidCalculationProjectMVC.Models
{
    public static class BidProjectFees
    {
        public static readonly decimal BasicUserFeePercentage = 0.1m;
        public static readonly decimal CommonCarMinBasicFee = 10.0m;
        public static readonly decimal CommonCarMaxBasicFee = 50.0m;
        public static readonly decimal LuxuryCarMinBasicFee = 25.0m;
        public static readonly decimal LuxuryCarMaxBasicFee = 200.0m;
        public static readonly decimal CommonSellerSpecialFee = 0.02m;
        public static readonly decimal LuxurySellerSpecialFee = 0.04m;
        public static readonly decimal AssociationFee = 0.04m;
        public static readonly decimal StorageFee = 100.0m;
    }
}

Models/EnumVehicleType.cs
namespace BidCalculationProjectMVC.Models
{
    public enum EnumVehicleType
    {
        Common,
        Luxury
    }
}

Models/ErrorViewModel.cs
namespace BidCalculationProjectMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/FeesCalculation/AssociationCostFee.cs
namespace BidCalculationProjectMVC.Models.FeesCalculation
{
    public class AssociationCostFee : IFee
    {
        public decimal CalculateFee(int vehicleType, decimal basePrice)
        {
            decimal result = basePrice switch
            {
                _ when basePrice >= 1 && basePrice < 500 => 5.0m,
                _ when basePrice >= 500 && basePrice < 1000 => 10.0m,
                _ when basePrice >= 1000 && basePrice < 3000 => 15.0m,
                _ when basePrice >= 3000 => 20.0m,
                _ => throw new NotImplementedException()
            };
            return result;
        }
    }
}

Models/FeesCalculation/BasicUserFee.cs
namespace BidCalculationProjectMVC.Models.FeesCalculation
{
    public class BasicUserFee : IFee
    {
        public decimal CalculateFee(int vehicleType, decimal basePrice)
        {

            var result = vehicleType switch
            {
                0 => CommonCar(basePrice),
                1 => LuxuryCar(basePrice),
                _ => throw new NotImplementedException()
            };
            return result;
        }

        private static decimal CommonCar(decimal basePrice)
        {
            var result = basePrice * BidProjectFees.BasicUserFeePercentage;
            var basicUserFee = result switch
            {
                _ when result < BidProjectFees.CommonCarMinBasicFee => BidProjectFees.CommonCarMinBasicFee,
                _ when result > BidProjectFees.CommonCarMaxBasicFee => BidProjectFees.CommonCarMaxBasicFee,
                _ => result
            };
            return basicUserFee;
        }

        private static decimal LuxuryCar(decimal basePrice)
        {
            var result = basePrice * BidProjectFees.BasicUserFeePercentage;
            var basicUserFee = result switch
            {
                _ when result < BidProjectFees.LuxuryCarMinBasicFee => BidProjectFees.LuxuryCarMinBasicFee,
                _ when result > BidProjectFees.LuxuryCarMaxBasicFee => BidProjectFees.LuxuryCarMaxBasicFee,
                _ => result
            };
            return basicUserFee;
        }


    }
}

Models/FeesCalculation/SellerSpecialFee.cs
namespace BidCalculationProjectMVC.Models.FeesCalculation
{
    public class SellerSpecialFee : IFee
    {
        public decimal CalculateFee(int vehicleType, decimal basePrice)
        {

            var result = vehicleType switch
            {
                0 => basePrice * BidProjectFees.CommonSellerSpecialFee,
                1 => basePrice * BidProjectFees.LuxurySellerSpecialFee,
                _ => throw new NotImplementedException()
            };
            return result;
        }
    }
}

Models/FeesCalculation/StorageFee.cs
namespace BidCalculationProjectMVC.Models.FeesCalculation
{
    public class StorageFee : IFee
    {
        public decimal CalculateFee(int vehicleType, decimal basePrice)
        {
            return BidProjectFees.StorageFee;
        }
    }
}

Models/VehicleViewModel.cs
namespace BidCalculationProjectMVC.Models
{
    public class VehicleViewModel
    {
        public decimal BasePrice { get; set; }
        public EnumVehicleType VehicleType { get; set; }

    }
}

Controllers/BidController.cs
using BidCalculationProjectMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BidCalculationProjectMVC.Controllers
{
    public class BidController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CalculateBid(VehicleViewModel vehicle)
        {
            try
            {
                var bidCalculator = new BidCalculator();
                var totalCost = bidCalculator.CalculateTotalCost(vehicle);

                ViewBag.TotalCost = totalCost;
                ViewBag.Vehicle = vehicle;                

                // Calculate fees and pass them to the view
                var fees = bidCalculator.GetFeesDetails(vehicle);
                ViewBag.Fees = fees;

                return View("Result");
            }
            catch (FormatException)
            {
                ModelState.AddModelError(string.Empty, "Error: Invalid input format. Please enter valid numeric values.");
                return View("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"An unexpected error occurred: {ex.Message}");
                return View("Index");
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using BidCalculationProjectMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;


namespace BidCalculationProjectMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Bid/Index.cshtml
@model VehicleViewModel

<h1>Welcome to the Car Auction Bid Calculator</h1>
<hr />

<form asp-action="CalculateBid" method="post">
    <div class="form-group">
        <label asp-for="BasePrice">Enter the Vehicle Base Price:</label>
        <input asp-for="BasePrice"  class="form-control" id="BPInput" required />
        <span asp-validation-for="BasePrice"></span>
    </div>

    <div class="form-group">
        <label asp-for="VehicleType">Enter the Vehicle Type (Common/Luxury):</label>
        @Html.DropDownListFor(model => model.VehicleType, Enum.GetNames(typeof(EnumVehicleType)).Select(t => new SelectListItem { Text = t, Value = t }), new { @class = "form-control" })
        <span asp-validation-for="VehicleType"></span>
    </div>
    <br>

    <button type="submit" class="btn btn-primary">Calculate Bid</button>
</form>

Views/Bid/Result.cshtml
@model VehicleViewModel

<h2>Calculation Result</h2>
<br />
<h4>Details of the Vehicle:</h4>

<ul>
<li>Base Price: @ViewBag.Vehicle.BasePrice.ToString("C")</li>
<li>Vehicle Type: @ViewBag.Vehicle.VehicleType</li>
</ul>

<h4>Fees Summary:</h4>
<ul>
    @foreach (var fee in ViewBag.Fees)
    {
        <li>@fee</li>
    }
</ul>
<p class="bold-text">Total Cost: @ViewBag.TotalCost.ToString("C")</p>

<a asp-controller="Bid" asp-action="Index" class="btn btn-primary">Make Another Bid</a>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BidCalculationProjectMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BidCalculationProjectMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Bid" asp-action="Index">BidCalculationProjectMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bid" asp-action="Index">Home</a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BidCalculationProjectMVC - Edgar Arturo Martínez
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>